ignore:
  - "topcoffea/modules/createJSON.py"    # Always done by hand
  - "topcoffea/modules/combine_json_ext.py"    # Always done  with `createJSON.py`
  - "topcoffea/modules/DASsearch.py"     # Cannot run DAS client on GitHub
  - "topcoffea/modules/fileReader.py"    # Only used when creating json files
  - "topcoffea/modules/HTMLGenerator.py" # Not currently using HTML generator
  - "topcoffea/modules/samples.py"       # Only used when creating json files
  - "topcoffea/plotter"                  # Not currently using plotter
  - "tests"                              # Don't need to inventory unit tests, they are covered by design
  - "setup.py"                           # Run only when installing TopCoffea
coverage:
  status:
    project:
      default:
        threshold: 90%
    patch:
      default:
        threshold: 90%
