name: CI

on:
  push:
  schedule:
    - cron: '0 1 * * *' # Test every day at 1AM
  
jobs:
  Full_Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH 

      - name: Install dependencies
        run: |
          conda config --set channel_priority strict
          conda config --add channels conda-forge
          conda env create -f environment.yml -n coffea-env

      - name: Conda list
        run: |
          conda list -n coffea-env

      - name: Install topcoffea package
        run: |
          conda run -n coffea-env pip install -e .

      - name: Download root files
        run: |
          wget --no-verbose http://www.crc.nd.edu/~kmohrman/files/root_files/for_ci/ttHJet_UL17_R1B14_NAOD-00000_10194.root

      - name: Run processors over test files with futures executor
        run: |
          conda install -y -n coffea-env -c conda-forge pytest pytest-cov root_base
          mkdir histos
          conda run -n coffea-env pytest tests/test_datacardmaker.py


      - name: Get yields 
        run: |
          cd analysis/topEFT
          conda run -n coffea-env python get_yield_json.py -f histos/output_check_yields.pkl.gz -n output_check_yields

      - name: Compare yields
        run: |
          cd analysis/topEFT
          conda run -n coffea-env python comp_yields.py output_check_yields.json test/UL17_private_ttH_for_CI_yields.json -t1 "New yields" -t2 "Ref yields"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          verbose: true
