name: CI

on:
  push:
  schedule:
    - cron: '0 1 * * *' # Should test every day at 1AM, though apparently does not work anywhere but master branch
  
jobs:
  # Example of a test job, just prints Hello world
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo Hello world
  # Placeholder job for conda stuff, based on coffea-job from https://github.com/cooperative-computing-lab/cctools-packaging-test/blob/main/.github/workflows/build.yml
  coffea-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test Coffea Build and Install
        run:
          cd tests
          chmod +x ./coffea_check.sh
         ./coffea_check.sh
  # Placeholder job for testing the processor, based on build job from https://github.com/bu-cms/bucoffea/blob/master/.github/workflows/pythonpackage.yml
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          #pip install -r requirements.txt # We will want to use conda for this type of thing?
      - name: Install package
        run: |
          pip install -e .
      - name: Run processors over test files
        run: |
          cd tests
          ./run_over_testfiles.sh
